import { Gabarito } from 'next/font/google'
import './globals.css'
import { NavBar } from '@/components/NavBar'

const font = Gabarito({ subsets: ['latin'] })

export const metadata = {
  title: 'MY ANIME LIST KW',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-color-dark `} suppressHydrationWarning={true}>
        <NavBar />
        {children}
        </body>
    </html>
  )
}
